services:
    traefik:
        image: traefik:v3.1
        command:
            - '--log.level=DEBUG'
        ports:
            - "80:80" # Expose HTTP
            - "8089:8080" # Expose Traefik dashboard
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./traefik-dynamic.yml:/dynamic.yaml:ro" # Mount dynamic configuration file
            - "./traefik.yml:/etc/traefik/traefik.yml:ro" # Static config
            - "./traefik-log.log:/var/traefik/log-file.log"

volumes:
  traefik-data:
    external: false
